global:
  resolve_timeout: 5m

route:
  receiver: pagerduty
  group_by: ['alertname', 'pod', 'namespace']
  group_wait: 10s
  group_interval: 30s
  repeat_interval: 1h

receivers:
  - name: pagerduty
    pagerduty_configs:
      - routing_key: "d48046ec59364a0bd0ab3f4847a4181b"
        severity: '{{ .CommonLabels.severity }}'
        description: '{{ .CommonAnnotations.summary }}'
